### ISSUE TITLE
readDataToEndOfFileAndReturnError requires macOS 10.15+

### ISSUE THREAD

**Issue by tsl-mousetail** [vitorgalvao/coffee-coffee-workflow#1]
### Workflow version

current version

### Alfred version

5.0.6

### macOS version

macOsS 10.14.6

### Debugger output

```alfred_debugger
It is not available with Alfred5
```

**Comment by tsl-mousetail** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/65294282/231921013-0f12c697-6304-47c7-90fa-b96020446383.png">

**Comment by vitorgalvao** [comment]
> It is not available with Alfred5

That is not output from the debugger. The form explains how to get that.

**Comment by vitorgalvao** [comment]
> It is not available with Alfred5

That is not output from [the debugger](> It is not available with Alfred5

That is not output from the debugger. The form explains how to get that). The form explains how to get that.

This has nothing to do with Alfred 5, your macOS version is too old and doesn’t support the required Apple Shortcut.

**Comment by vitorgalvao** [comment]
> current version

Please always share the *exact* version. Developers are often on different releases from users and “current” or “latest” is fuzzy (latest beta, stable, pre-release?). Plus, it makes it harder for others who arrive later to identify if the issue applies to them. To provide informed help it is imperative that we work with precise information.

> It is not available with Alfred5

It *does* work on Alfred 5. That’s not output from [the debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) like the template asks. Without that it’s impossible to say what’s happening.

**Comment by tsl-mousetail** [comment]
this is debug log:

[19:29:49.206] Logging Started...
[19:29:58.146] Coffee Coffee[Script Filter] Queuing argument ''
[19:29:58.326] Coffee Coffee[Script Filter] Script with argv '' finished
[19:29:58.330] ERROR: Coffee Coffee[Script Filter] Code 1: /Users/xxxxxx/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/A992F58C-CEF8-49D3-9362-C3DF7234BD22:725:833: execution error: Error on line 31: TypeError: stdout.fileHandleForReading.readDataToEndOfFileAndReturnError is not a function. (In 'stdout.fileHandleForReading.readDataToEndOfFileAndReturnError(false)', 'stdout.fileHandleForReading.readDataToEndOfFileAndReturnError' is undefined) (-2700)

**Comment by vitorgalvao** [comment]
That is caused by your older installation of macOS. That API is only supported on macOS 10.15 and above.

An [older version](https://github.com/vitorgalvao/coffee-coffee-workflow/releases) might work for you but this is otherwise working as intended, the previous method was deprecated.
