### ISSUE TITLE
Ability to customize the default behavior ("macOS" or "macOS + screen")

### ISSUE THREAD

**Issue by dmitry-ivanov** [vitorgalvao/coffee-coffee-workflow#4]
### Feature details

Hey,

Thanks for your work and the great workflow!

I've seen that there's a possibility to prevent screen from sleeping (by using `Cmd`+`Enter`).

However, I find myself always forgetting about it.

If possible, it would be really great to have the ability to choose the default behavior, something like:

By default, prevents from sleeping: _[select]_
- macOS
- macOS and screen

So, a user chooses what he prefers for the `Enter` action, and the second option goes to `Cmd`+`Enter`.

Thank you,
Dmitry

**Comment by vitorgalvao** [comment]
Thank you for the kind words.

I started looking into it but it’s going to require non-trivial changes and no one else is asking for it after a decade of the workflow being available, so it keeps getting bumped down the list of priorities.

The workflow seldom changes so I recommend you edit it locally instead. All you need to do is double click each of these connections and switch them around.

<img width="91" alt="image" src="https://github.com/user-attachments/assets/f4efc6ad-05d4-4100-a44b-9e124f65513c">

Make the top one use <kbd>⌘</kbd> (and make it whatever message you want) and the bottom one have no modifiers.

**Comment by dmitry-ivanov** [comment]
Got it, thank you! 👍

**Comment by tarvy** [comment]
Nice! had the same question
